### ISSUE TITLE
图片名和路径问题

### ISSUE THREAD

**Issue by ghost** [ZhelinCheng/ghost-qcloud-cos#1]
您好，谢谢你开发的这个应用。
我正在使用这个应用把腾讯oss作为Ghost 图床。有两个问题请教：
1. 如果在上传时保持图片名不变，现在上传后，图片名是重新随机生成的，不方面图片复用。
2. 如何自定义图片储存的文件夹，现在上传后，会在Oss中建立ghost/content/images/文件夹，也不方面图片复用。
谢谢。

**Comment by ZhelinCheng** [comment]
这两个问题都是下面一个解决方案，
你需要先fork一份代码，并使用Git的方式安装。
在index.js第72/73行，稍微修改一下：
```
return `/ghost/content/images/${YY}/${MM}/${file.name}`
```

**Comment by ghost** [comment]
按照你的方法，问题解决了，谢谢！
