### ISSUE TITLE
Old instance migration

### ISSUE THREAD

**Issue by ljy19891118** [ZhelinCheng/ghost-qcloud-cos#10]
Hi Cheng,

I'm glad to deploy your adapter for Tencent COS in my Ghost Website.

However, after I finished all the setting and restart Ghost, none post could open normally, and show me a 400 like this:

<img width="486" alt="image" src="https://user-images.githubusercontent.com/13805095/170210565-7bb026e9-b47c-4bb1-8ef3-baa54b941325.png">

Even I create a totally new post and publish it, I find the images have been already uploaded onto the Tencent COS,  it's still showing the 400 now.

My configure like this:
`
{
  "url": "https://............",
  "server": {
    "port": 2368,
    "host": "127.0.0.1"
  },
  "database": {
    "client": "mysql",
    "connection": {
      "host": "......",
      "user": "......",
      "password": "......,
      "database": "........"
    }
  },
  "mail": {
    "transport": "Direct"
  },
  "logging": {
    "transports": [
      "file",
      "stdout"
    ]
  },
  "process": "systemd",
  "paths": {
    "contentPath": "/var/www/blog/content"
  },
  "storage": {
    "active": "ghost-qcloud-cos",
    "ghost-qcloud-cos": {
      "SecretId": ".......",
      "SecretKey": ".......",
      "Bucket": ".......",
      "Region": "ap-beijing"
    }
  }
}
`

Looking forward your reply, thanks.

**Comment by ZhelinCheng** [comment]
把cos相关配置取消掉呢？可以正常访问吗？顺便看看这个错误是不是响应的403

**Comment by ljy19891118** [comment]
是的，当COS相关配置移除后，一切回复正常。

浏览器控制台中看到不是403，就是400
<img width="502" alt="image" src="https://user-images.githubusercontent.com/13805095/170221101-0f7b299c-62b9-4106-98a7-4d14f1beaf81.png">

BTW, Ghost version is 4.41.3

**Comment by ljy19891118** [comment]
是的，当COS相关配置移除后，一切回复正常。

浏览器控制台中看到不是403，就是400
<img width="502" alt="image" src="https://user-images.githubusercontent.com/13805095/170221101-0f7b299c-62b9-4106-98a7-4d14f1beaf81.png">

BTW, Ghost version is 4.41.3

**Comment by ljy19891118** [comment]
是的，当COS相关配置移除后，一切回复正常。

浏览器控制台中看到不是403，就是400
<img width="502" alt="image" src="https://user-images.githubusercontent.com/13805095/170221101-0f7b299c-62b9-4106-98a7-4d14f1beaf81.png">

BTW, Ghost version is 4.41.3

**Comment by ZhelinCheng** [comment]
因为安装依赖的时候可能会用到root权限，你可以看看`content/adapters/storage`这个目录的所属组和用户是不是ghost，不是的话改一下看看。

**Comment by ljy19891118** [comment]
确实不是ghost，但是修改为ghost后，问题依旧😅

**Comment by ZhelinCheng** [comment]
这就很尴尬了，我自己也是用的这个，要不你换一个安装方式？

**Comment by ljy19891118** [comment]
另外一种安装方式也不行，于是我尝试将Ghost升级到最新的版本，但是Ghost最近发生了大版本升级，不再支持MySQL5.*，于是我将Ghost迁移到了有8.0数据库的服务器，重新试了您的adapter，结果就好了。
因为环境变化太大，我也不确定是那个原因修复了这问题，但我想将解决的过程告诉您知道。
