### ISSUE TITLE
image asset URLs (Cover Image, Favicon Image and Post featured images etc) are not fully qualified URLs

### ISSUE THREAD

**Issue by ghost** [ZhelinCheng/ghost-qcloud-cos#3]
Example URL -
Icon Image: `//inote-1251069384.cos.ap-nanjing.myqcloud.com/ghost/content/images/2020/03/d370cff0ecf4558e.png`,
Cover Image": `//inote-1251069384.cos.ap-nanjing.myqcloud.com/ghost/content/images/2020/03/702c1c364808ab0b.jpg`

One of the resolutions is to add protocol (https:) to image assets. Once done, Draftbox will be able to source image assets and content.

使用 腾讯cos 作为ghost 图床后，Gatsby 无法获取 图片，如何处理

**Comment by ZhelinCheng** [comment]
更新了一个版本，你看看

**Comment by ghost** [comment]
貌似，所有图片 url  都是 //xxx.jpg 而不是 https://xxx.jpg。 
此情况下，Gatsby 无法获取ghost cms  图片 url。能否更新下？

**Comment by ZhelinCheng** [comment]
@xiyizhou 可以

**Comment by ghost** [comment]
> @xiyizhou 可以

同学，啥时候更新URL 为 https 格式啊

**Comment by ZhelinCheng** [comment]
> > @xiyizhou 可以
> 
> 同学，啥时候更新URL 为 https 啊

忘了这事，明天更新
