### ISSUE TITLE
更新后，上传图片失败，提示Request was rejected due to server error

### ISSUE THREAD

**Issue by ghost** [ZhelinCheng/ghost-qcloud-cos#4]
OS: Ubuntu, v18.04.5 LTS
    Node Version: v12.18.3
    Ghost Version: 3.30.0
    Ghost-CLI Version: 1.14.1
    Environment: production

  "storage": {
    "active": "cos-store",
    "cos-store": {
      "SecretId": "A2IDuZSiPHUMjb8FGZaUR32UKmgA6oQ1L74m",
      "SecretKey": "H57J4M7gSmlPuPr85ucfdm44wrTTINoT",
      "Bucket": "inote-11111111",
      "Region": "ap-nanjing"
    }
  },

**Comment by ZhelinCheng** [comment]
重新填写一下配置信息，新增了几个参数，但按道理是不会影响到的。
备注：记得更改你的SecretKey，你直接写出来不太安全。

**Comment by ghost** [comment]
> 重新填写一下配置信息，新增了几个参数，但按道理是不会影响到的。
> 备注：记得更改你的SecretKey，你直接写出来不太安全。

还是不可以，与 nodejs 本版有关吗

**Comment by ZhelinCheng** [comment]
> > 重新填写一下配置信息，新增了几个参数，但按道理是不会影响到的。
> > 备注：记得更改你的SecretKey，你直接写出来不太安全。
> 
> 还是不可以，与 nodejs 本版有关吗

我刚刚试了试，按照你这样配置也没有问题，你本地起一个试一试呢？

**Comment by ghost** [comment]
按这个设置在本地是正常的，我用的腾讯云服务器，是否要开放特定端口，已开放TCP:22,3389,80,443,20,21,2368,465；
云存储是否要做额外设置，谢谢，完全技术小白，劳烦指点

**Comment by ZhelinCheng** [comment]
云存储不需要额外的设置了，我现在自己也在用，并没有出现这个问题

**Comment by ghost** [comment]
> 云存储不需要额外的设置了，我现在自己也在用，并没有出现这个问题

能否留个邮箱，我把腾讯云账号 提供给你或者 你复制份镜像 给我，实在搞不定了

**Comment by ZhelinCheng** [comment]
@xiyizhou 邮箱在我首页，你直接发SecretId和SecretKey给我即可

**Comment by ghost** [comment]
已发 万分感谢

**Comment by xiyizhou** [comment]
换一台腾讯云服务器试了下，还是老问题
![Snipaste_2020-08-25_07-39-51](https://user-images.githubusercontent.com/55862635/91106813-44b69f00-e6a6-11ea-8b03-f30da3bdbec1.jpg)

**Comment by ZhelinCheng** [comment]
@xiyizhou 这跟服务器关系不大

**Comment by ZhelinCheng** [comment]
@xiyizhou 你Bucket乱填的？？？

**Comment by xiyizhou** [comment]
> @xiyizhou 你Bucket乱填的？？？

发你邮箱的是正确的

**Comment by ZhelinCheng** [comment]
@xiyizhou 你把你的完整配置发给我一下

**Comment by xiyizhou** [comment]
> @xiyizhou 你把你的完整配置发给我一下

已发 谢谢

**Comment by ghost** [comment]
文件夹权限问题，部署完成后，运行`sudo chown -R <user>:<user> ./content`，再运行`ghost setup linux-user systemd`，问题解决
