### ISSUE TITLE
请问base url 和 base Url分别是什么

### ISSUE THREAD

**Issue by forrany** [ZhelinCheng/ghost-qcloud-cos#7]
我这边base url 和 path 设置为空，上传后正确获取上传图片到地址，去腾讯云存储没有看到上传的图片，应该是没有上传成功
控制台报错
![image](https://user-images.githubusercontent.com/29779326/111113977-8dc83500-859d-11eb-9338-10f36cf4a449.png)

**Comment by ZhelinCheng** [comment]
路径错误，少了ghost少了一个/
