### ISSUE TITLE
通过NPM安装出现如下状况

### ISSUE THREAD

**Issue by aihoom** [ZhelinCheng/ghost-qcloud-cos#8]
Message: Ghost was able to start, but errored during boot with: Unable to find storage adapter cos-store in ,/www/此处是路径

请求大佬帮忙解决。。

另通过GIT方式也出现了一个错误Ghost was able to start, but errored during boot with: Cannot read property 'Bucket' of undefined

顺便一提：
Debug Information:
    OS: Ubuntu, v20.04.2 LTS
    Node Version: v14.17.2
    ** Ghost Version: 4.9.4 **
    Ghost-CLI Version: 1.17.3
    Environment: production
    Command: 'ghost start'

**Comment by ZhelinCheng** [comment]
看样子是配置错误
